language: go

go:
  - 1.7

branches:
  only:
    - master

before_install:
#- ./look_for_logs.sh
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- go get github.com/golang/lint/golint
- go get github.com/GeertJohan/fgt
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi

install:
- go get -t -v -d

script:
- fgt golint $(find . | grep .go$ | grep -v led.pb.go | grep -v lib.go)
- go test -covermode=count -coverprofile=profile.cov -tags=maintest
- $HOME/gopath/bin/goveralls -service=travis-ci -ignore=led.go,lib/lib.go -package github.com/brotherlogic/led -coverprofile=$HOME/gopath/src/github.com/brotherlogic/led/profile.cov

